"""empty message

Revision ID: 18fdc2367188
Revises: 01b82dba39d9
Create Date: 2024-12-17 13:54:11.814937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18fdc2367188'
down_revision = '01b82dba39d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favoriteplanets')
    op.drop_table('favoritepeople')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favoritepeople',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('people_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['people_id'], ['people.uid'], name='favoritepeople_people_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='favoritepeople_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='favoritepeople_pkey')
    )
    op.create_table('favoriteplanets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('planet_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['planet_id'], ['planets.uid'], name='favoriteplanets_planet_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='favoriteplanets_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='favoriteplanets_pkey')
    )
    # ### end Alembic commands ###
